### ISSUE TITLE
OK_CONNECT_PORTS = {443, 8443}

### ISSUE THREAD

**Issue by TadavomnisT** [jab/trio_http_proxy#1]
Hi!
Incredible proxy-server you've built. Thanks.

But it puzzled me though, Why would you set a limitation for ports in `CONNECT` method?

As far as I know, An HTTP-server can be running on any free port. Does it have to do something with SSL? 

_____________________

I tried to proxy a `TCP` connection using your script (`netcat` TCP server to be exact) , and there I noticed the **assert** saying: it only works if my server is running on `443` or `8443` ports!

**Comment by jab** [comment]
Thanks for reporting! I can't remember what I was thinking when I added that `assert`. Removed in the latest revision.

Out of curiosity, how'd you find this project? :)

**Comment by TadavomnisT** [comment]
@jab 
You're quite welcome :*

A friend told me about it: @SafaSafari , Not sure how did he find it, google search maybe...
